export { default as Categories } from './categories/Categories'
export { default as Products } from './products/Products'
export { default as ProductDetail } from './product-detail/ProductDetail'
export { default as Cart } from './cart/Cart'
export { default as Orders } from './orders/Orders'